version: '3.8'

services:
  whatsapp-drive-assistant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_DRIVE_CREDENTIALS_FILE=/app/credentials/credentials.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - API_SERVER_URL=${API_SERVER_URL:-http://localhost:5000}
      - FLASK_ENV=production
      - PORT=5000
      - LOG_LEVEL=INFO
    volumes:
      - ./credentials:/app/credentials
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whatsapp-drive-assistant
    restart: unless-stopped
    profiles:
      - production

volumes:
  credentials:
  logs:
  data:
